M48
; DRILL file {KiCad (6.0.11)} date Tue Sep 12 01:08:27 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-12T01:08:27+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1220
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T2
X4.0921Y-2.1551
X4.0921Y-6.4858
X8.0291Y-6.4858
T1
G00X6.3405Y-5.4781
M15
G01X6.3405Y-5.4309
M16
G05
T0
M30
