M48
; DRILL file {KiCad (6.0.7)} date Tue Dec 12 10:26:36 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-12T10:26:36+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X0.6954Y-0.7023
X0.6954Y-2.3164
X3.2938Y-0.7023
X3.2938Y-2.3164
T0
M30
