M48
; DRILL file {KiCad (6.0.11)} date Wed Sep 13 23:25:57 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-13T23:25:57+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.8213Y-1.9083
X3.8213Y-5.0579
X7.7583Y-1.9083
X7.7583Y-5.0579
T0
M30
